name: SamWorobec
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61003
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191820'
    - '#737e84'
    - '#395b7e'
    - '#b0a17d'
    - '#e1e1e1'
  brandStrength: 0.0625
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
