name: Sam Worobec
favicon: null
layout_spectrum: 0.6126
typography_spectrum: 0.61003
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#100702'
    - '#fffd38'
    - '#fda729'
    - '#aaa09f'
    - '#6d6b79'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
